---
# file: roles/desktop/tasks/main.yml

- name: install_repositories_additional_keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{ item }}'
  with_items:
    - 7721F63BD38B4796      # chrome
    - EB3E94ADBE1229CF      # vscode

- name: install_repositories_additional
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    - ppa:ansible/ansible
    - ppa:linrunner/tlp
    - ppa:papirus/papirus
    - ppa:ultradvorka/ppa

- name: install_repositories_additional_vscode
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    filename: vscode

- name: disable_repository_creation_chrome
  copy:
    content: ""
    dest: /etc/default/google-chrome
    owner: root
    group: root
    mode: 0644

- name: accept_mscorefonts_license
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    value: 'true'
    vtype: select

- name: remove_packages
  apt:
    name: "{{ query('flattened', ['{{ packages_remove }}']) }}"
    state: absent
    purge: yes

- name: install_packages
  apt:
    name: "{{ query('flattened', ['{{ packages_base }}', '{{ packages_misc }}', '{{ packages_devel }}', '{{ packages_devel_libs }}', '{{ packages_xdeps }}', '{{ packages_xapps }}']) }}"

- name: add_user_to_docker_group
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: yes
    state: present

- name: install_config_systemd_journalsize
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^#?SystemMaxUse='
    line: 'SystemMaxUse=50M'

- name: install_config_gdm_disable_wayland
  lineinfile:
    dest: /etc/gdm3/custom.conf
    regexp: '^#?WaylandEnable='
    line: 'WaylandEnable=false'

- name: create_xorg_config_dir
  file:
    path: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: install_config_xorg_tweaks_mouse
  copy:
    src: 20-mouse-tweaks.conf
    dest: /etc/X11/xorg.conf.d/20-mouse-tweaks.conf
    owner: root
    group: root
    mode: 0644

- name: install_config_xorg_tweaks_touchpad
  copy:
    src: 20-touchpad-tweaks.conf
    dest: /etc/X11/xorg.conf.d/20-touchpad-tweaks.conf
    owner: root
    group: root
    mode: 0644
