---
# file: roles/common/tasks/main.yml

- name: preinstall_packages
  apt:
    name: "{{ query('flattened', ['{{ packages_preinstall }}']) }}"

- name: install_repositories_additional_keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '{{ item }}'
  with_items:
    - 8D81803C0EBFCD88    # docker

- name: install_repositories_additional
  apt_repository:
    repo: '{{ item }}'
  with_items:
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: install_packages
  apt:
    name: "{{ query('flattened', ['{{ packages_base }}', '{{ packages_misc }}', '{{ packages_devel }}', '{{ packages_docker }}']) }}"

- name: optimize_disk_io_schedulers
  copy:
    src: 60-io_schedulers.rules
    dest: /etc/udev/rules.d/60-io_schedulers.rules
    owner: root
    group: root
    mode: 0644
