---
# file: roles/common/vars/main.yml

packages_preinstall:
  - apt-transport-https
  - curl
  - gnupg-agent
  - software-properties-common

packages_base:
  - amd64-microcode
  - haveged
  - intel-microcode
  - lm-sensors
  - openssh-server
  - smartmontools

packages_misc:
  - git
  - htop
  - iotop
  - mercurial
  - p7zip
  - rar
  - screen
  - traceroute
  - unrar
  - unzip
  - vim
  - wget
  - zip
  - zsh

packages_devel:
  - autoconf
  - automake
  - bison
  - build-essential
  - flex
  - libtool
  - linux-headers-{{ ansible_kernel }}

packages_docker:
  - docker-ce
  - docker-ce-cli
  - containerd.io
